package main

import "interview-code-practice/problems"

func main() {
	problems.ReverseString()
	problems.PalindromeChecker()
	problems.SwapTwoNumbers()
	problems.FindingLargestNumber()
	problems.FindingSamllestNumber()
	problems.CountingVowelsConsonants()
	problems.CharacterCounter()
	problems.Fibonacci()
	problems.SumDigits()
	problems.RemoveDuplicatsArray()
	problems.ReverseWordString()
	problems.EvenOddFinder()
	problems.FindStringLength()
	problems.StringToInt()
	problems.EvenOddIndex()
	problems.ArrayReverse()
	problems.CheckArraySort()
	problems.CaseConvertion()
	problems.SecondLargestElement()
	problems.CheckTwoStringAnagram()
	problems.FindMissingElements()
	problems.SortArray()
	problems.FirstNonRepeatingChar()
	problems.CommonElementsOfTwoAray()
	problems.ReverseSentence()
	problems.PairSumFinder()
	problems.MergeTwoSortedArray()
	problems.RemoveAllWhiteSpace()
	problems.ExtractDigitsAndAlphat()
	problems.MoveZeroToEnd()
	problems.RemoveElements()
	problems.RotateArray()
	problems.PrimeNumbers()
	problems.TwoSum()
	problems.SearchRotatedSortIndex()
	problems.FindTheMaximumSumOfSubArray()
	problems.TopKfreqElement()

}
